# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ml-explore',
                'doc_host': 'https://lsa-pilot.github.io',
                'git_url': 'https://github.com/lsa-pilot/ml-explore',
                'lib_path': 'ml_explore'},
  'syms': {'ml_explore.core': {'ml_explore.core.foo': ('core.html#foo', 'ml_explore/core.py')}}}
